lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
title: Altera Wiki
description: "Great site about Altera Wiki."

# Build settings
remote_theme: jekyll/minima
