
# Site settings
title: Altera Wiki
author:
  name: Altera

description: "Community Wiki to share knowledge."

# Build settings
theme: minima
plugins:
  - jekyll-feed


###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Author's home: "https://altera.com/"
