lsi: false
safe: true
source: https://github.com/altera-wiki
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
title: Altera Wiki
author:
  name: Altera

url: https://altera.com/
description: "Community Wiki to share knowledge."

# Build settings
remote_theme: jekyll/minima
